"""empty message

Revision ID: 0c605692a86d
Revises: 6f4d93e0bf95
Create Date: 2024-06-10 14:51:21.894202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c605692a86d'
down_revision = '6f4d93e0bf95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_mood_table_user_id_users_table'), 'users_table', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_mood_table_user_id_users_table'), type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
