"""empty message

Revision ID: 20b7297b35fc
Revises: bdde0c706a60
Create Date: 2024-06-13 17:39:20.901810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b7297b35fc'
down_revision = 'bdde0c706a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications_table', schema=None) as batch_op:
        batch_op.alter_column('renew_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications_table', schema=None) as batch_op:
        batch_op.alter_column('renew_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
