"""empty message

Revision ID: bdde0c706a60
Revises: a7befd3ab22a
Create Date: 2024-06-13 14:09:28.650509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdde0c706a60'
down_revision = 'a7befd3ab22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diary_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('header', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('journal_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_table.id'], name='fk_diary_table_journal_id_journal_table'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
